import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY; // Assumed to be available
const ai = new GoogleGenAI({ apiKey: apiKey });

// --- IMAGE EDITING ---
export const editImageWithGemini = async (
  base64Image: string,
  prompt: string
): Promise<string> => {
  if (!apiKey) throw new Error("API Key not found");

  try {
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          { inlineData: { mimeType: 'image/png', data: cleanBase64 } },
        ],
      },
    });

    let generatedImage = "";
    if (response.candidates && response.candidates.length > 0) {
       for (const part of response.candidates[0].content.parts) {
         if (part.inlineData) {
           generatedImage = `data:image/png;base64,${part.inlineData.data}`;
           break;
         }
       }
    }
    if (!generatedImage) throw new Error("No image generated by Gemini.");
    return generatedImage;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

// --- IMAGE GENERATION (Nano Banana Pro) ---
export const generateImageWithGemini = async (
  prompt: string,
  size: '1K' | '2K' | '4K' = '1K'
): Promise<string> => {
  if (!apiKey) throw new Error("API Key not found");

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          imageSize: size,
          aspectRatio: "1:1"
        }
      }
    });

    let generatedImage = "";
    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImage = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }
    if (!generatedImage) throw new Error("No image generated.");
    return generatedImage;
  } catch (error) {
    console.error("Image Generation Error:", error);
    throw error;
  }
};

// --- CHAT & SEARCH ---
export const chatWithGemini = async (
  history: { role: 'user' | 'model', parts: { text: string }[] }[],
  message: string,
  useSearch: boolean = false
) => {
  if (!apiKey) throw new Error("API Key not found");

  // Use Flash for Search (as per requirements) or Pro for Logic
  const model = useSearch ? 'gemini-3-flash-preview' : 'gemini-3-pro-preview';
  
  try {
    const config: any = {};
    if (useSearch) {
      config.tools = [{ googleSearch: {} }];
    }

    const response = await ai.models.generateContent({
      model: model,
      contents: [
        ...history,
        { role: 'user', parts: [{ text: message }] }
      ],
      config: config
    });

    const text = response.candidates?.[0]?.content?.parts?.[0]?.text || "No response text.";
    
    // Extract grounding chunks if available
    let groundingUrls: { title: string, uri: string }[] = [];
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    if (chunks) {
      chunks.forEach((c: any) => {
        if (c.web) {
          groundingUrls.push({ title: c.web.title, uri: c.web.uri });
        }
      });
    }

    return { text, groundingUrls };
  } catch (error) {
    console.error("Chat Error:", error);
    throw error;
  }
};

// --- AUDIO TRANSCRIPTION ---
export const transcribeAudio = async (base64Audio: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key not found");

  try {
    const cleanBase64 = base64Audio.replace(/^data:audio\/(wav|mp3|ogg|webm);base64,/, "");
    
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          { text: "Transcribe the following audio exactly as spoken." },
          { inlineData: { mimeType: 'audio/wav', data: cleanBase64 } }
        ]
      }
    });

    return response.text || "Could not transcribe.";
  } catch (error) {
    console.error("Transcription Error:", error);
    throw error;
  }
};

export const getLiveClient = () => {
    return ai;
}